export enum Departments {
  // Academic Departments
  CSE = 'Computer Science and Engineering (CSE)',
  IPE = 'Industrial and Production Engineering (IPE)',
  PME = 'Petroleum and Mining Engineering (PME)',
  ChE = 'Chemical Engineering (ChE)',
  EEE = 'Electrical and Electronic Engineering (EEE)',
  BME = 'Biomedical Engineering (BME)',
  TE = 'Textile Engineering (TE)',
  MB = 'Microbiology (MB)',
  FMB = 'Fisheries and Marine Bioscience (FMB)',
  GEBT = 'Genetic Engineering and Biotechnology (GEBT)',
  PHAR = 'Pharmacy (PHAR)',
  BMB = 'Biochemistry and Molecular Biology (BMB)',
  EST = 'Environmental Science and Technology (EST)',
  NFT = 'Nutrition and Food Technology (NFT)',
  FE = 'Food Engineering (FE)',
  CDM = 'Climate and Disaster Management (CDM)',
  PESS = 'Physical Education and Sports Science (PESS)',
  PTR = 'Physiotherapy and Rehabilitation (PTR)',
  NHS = 'Nursing and Health Science (NHS)',
  ENG = 'English (ENG)',
  PHY = 'Physics (PHY)',
  CHEM = 'Chemistry (CHEM)',
  MATH = 'Mathematics (MATH)',
  ASDS = 'Applied Statistics and Data Science (ASDS)',
  AIS = 'Accounting and Information Systems (AIS)',
  MGT = 'Management (MGT)',
  MKT = 'Marketing (MKT)',
  FB = 'Finance and Banking (FB)',
  DVM = 'Veterinary Medicine (DVM)',

  // Faculties
  FET = 'Faculty of Engineering & Technology',
  FAST = 'Faculty of Applied Science & Technology',
  FBST = 'Faculty of Biological Science & Technology',
  FHS = 'Faculty of Health Science',
  FS = 'Faculty of Science',
  FVM = 'Faculty of Veterinary Medicine',
  FASS = 'Faculty of Arts and Social Science',
  FBS = 'Faculty of Business Studies',

  // Offices
  VC = 'Office of the Vice Chancellor',
  TREASURER = 'Office of the Treasurer',
  REGISTRAR = 'Office of the Registrar',
  ICT = 'Office of the ICT Cell',
  LIBRARIAN = 'Office of the Librarian',
  PROCTOR = 'Office of the Proctor',
  COUNSELING = 'Office of the Student Counseling and Guidance',
  ACCOUNTS = 'Office of the Director of Accounts',
  PLANNING = 'Office of the Director of Planning, Development & Works',
  CONTROLLER = 'Office of the Controller of Examinations',
  ENGINEER = 'Office of the Chief Engineer',
  MEDICAL = 'Office of the Chief Medical Officer',
  TRANSPORT = 'Office of the Transport Administrator',
  AUDIT = 'Audit Cell',
  PR = 'Public relation branch (Registrar Office)',

  // Halls
  SMRH = 'Shaheed Mashiur Rahman Hall',
  TRH = 'Taposhi Rabeya Hall',
  MMMH = 'Munshi Mohammad Meherullah Hall',
  BTBH = 'Beerprotik Taramon Bibi Hall',

  // Institutes & Centers
  IHER = 'Institute for Higher Education and Research (IHER)',
  RESEARCH_CELL = 'Office of the Research Cell',
  IQAC = 'Institutional Quality Assurance Cell (IQAC)',
  CSIRL = 'CSIRL',
  GENOME = 'Genome Centre',
  ISC = 'International Service Center (ISC)',
  PE = 'Office of the Physical Education',
  TSC = 'Teachers and Students Centre (TSC)',
  CYBER = 'Cyber Centre',
  FISH = 'Modern Fish Hatchery and Wet Lab',
}
