// departments.ts
export const departments = [
  'Computer Science and Engineering (CSE)',
  'Industrial and Production Engineering (IPE)',
  'Petroleum and Mining Engineering (PME)',
  'Chemical Engineering (ChE)',
  'Electrical and Electronic Engineering (EEE)',
  'Biomedical Engineering (BME)',
  'Textile Engineering (TE)',
  'Microbiology (MB)',
  'Fisheries and Marine Bioscience (FMB)',
  'Genetic Engineering and Biotechnology (GEBT)',
  'Pharmacy (PHAR)',
  'Biochemistry and Molecular Biology (BMB)',
  'Environmental Science and Technology (EST)',
  'Nutrition and Food Technology (NFT)',
  'Food Engineering (FE)',
  'Climate and Disaster Management (CDM)',
  'Physical Education and Sports Science (PESS)',
  'Physiotherapy and Rehabilitation (PTR)',
  'Nursing and Health Science (NHS)',
  'English (ENG)',
  'Physics (PHY)',
  'Chemistry (CHEM)',
  'Mathematics (MATH)',
  'Applied Statistics and Data Science (ASDS)',
  'Accounting and Information Systems (AIS)',
  'Management (MGT)',
  'Marketing (MKT)',
  'Finance and Banking (FB)',
  'Veterinary Medicine (DVM)',
];

// offices.ts
export const offices = [
  'Faculty of Engineering & Technology',
  'Faculty of Applied Science & Technology',
  'Faculty of Biological Science & Technology',
  'Faculty of Health Science',
  'Faculty of Science',
  'Faculty of Veterinary Medicine',
  'Faculty of Arts and Social Science',
  'Faculty of Business Studies',
  'Office of the Vice Chancellor',
  'Office of the Treasurer',
  'Office of the Registrar',
  'Office of the ICT Cell',
  'Office of the Librarian',
  'Shaheed Mashiur Rahman Hall',
  'Taposhi Rabeya Hall',
  'Munshi Mohammad Meherullah Hall',
  'Beerprotik Taramon Bibi Hall',
  'Office of the Proctor',
  'Office of the Student Counseling and Guidance',
  'Office of the Director of Accounts',
  'Office of the Director of Planning, Development & Works',
  'Office of the Controller of Examinations',
  'Office of the Chief Engineer',
  'Office of the Chief Medical Officer',
  'Institute for Higher Education and Research (IHER)',
  'Office of the Research Cell',
  'Institutional Quality Assurance Cell (IQAC)',
  'CSIRL',
  'Genome Centre',
  'International Service Center (ISC)',
  'Office of the Physical Education',
  'Office of the Transport Administrator',
  'Audit Cell',
  'Public relation branch (Registrar Office)',
  'Teachers and Students Centre (TSC)',
  'Cyber Centre',
  'Modern Fish Hatchery and Wet Lab',
];
